# Generated by Django 4.2.1 on 2025-02-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="complete",
            new_name="status",
        ),
    ]
