services:
  backend:
    container_name: django_adv_alibigdeli_backend
    image: django_adv_alibigdeli_backend
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=test
    volumes:
      - ./backend:/app
    command:  python manage.py runserver 0.0.0.0:8000

  smtp4dev:
    container_name: django_adv_alibigdeli_smtp4dev
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5500:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      #Specifies the URLs the web UI will use inside the container.
      - ServerOptions__Urls=http://*:80

      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data: